create database healthcare_db;
use healthcare_db;

drop database healthdare_db;

/* 1. Count the number of patients whose gender is "Female" and are above 50 years old.*/

select count(*) as no_of_patient
from hospital_data
where Gender= "Female" and age > 50; 

/* 2.	Find the total number of patients admitted for each age group.(0-18, 19-35, 36-50, 51+) */

select case when age between 0 and 18 then "0-18"
     when age between 19 and 35 then "19-35"
     when age between 36 and 50 then "36-50"
     when age > 50 then "51+"
     end as age_group, count(*) as total_patients
From hospital_data
group by age_group
order by age_group;

/* 3.	% of Patients admitted with cancer*/

with total as
(select count(distinct(Name)) as total_patient
from hospital_data),

canc as 
(select count(distinct(Name)) as cancer_patient
from hospital_data
where Medical_Condition = "cancer")

select c.cancer_patient, t.total_patient,
round(( c.cancer_patient*100/ t.total_patient),2) as cancer_patient_pct
from total t 
join canc c 
on 1=1;

/* 4.	Find the total revenue generated by each hospital.*/

select hospital, round(sum(billing_amount),2) as revenue
from hospital_data
group by hospital
order by revenue desc limit 5;

/* 5.	Retrieve the details of patients whose billing amount is above the average billing amount*/

select distinct(name) as patient,billing_amount
from hospital_data
where billing_amount  > (select avg(billing_amount) as avg_billing_amount
from hospital_data)
order by billing_amount desc limit 10;

/* 6.	Find the top doctor from each hospital who responsible for the highest percentage revenue in hospital */

with doc as 
(select hospital, doctor, sum(billing_amount) as bill
from hospital_data
group by doctor, hospital
order by bill desc limit 10),

hos as 
(select hospital, sum(billing_amount) as total_rev
from hospital_data
group by hospital
order by total_rev desc limit 10),

 pct as
(select h.hospital, d.doctor,
(bill/ total_rev)*100 as doc_pct_rev
from doc d  
join hos h 
on 1=1),

rnk_cte as (select hospital, doctor,
rank() over (partition by h.hospital order by doc_pct_rev desc) as rnk
from pct)

select hospital, doctor, rnk
from rnk_cte
 where rnk =1;
 
 /* 7.	find the top 5 doctors who treated highest number of patients.*/
 
 select doctor,  count(name) as patient_count
 from hospital_data
 group by doctor 
 order by patient_count desc 
 limit 5;
 
 /* 8.	Find Cardiology Specialist doctors ( who treated most patient).*/
 
 with special as 
 (select doctor, count(*) as total
 from hospital_data
 where medical_condition = "asthma"
 group by doctor
 order by total desc),
 
 top as 
 (select doctor,
 dense_rank() over(order by total desc) as top
 from special)
 
select doctor as asthma_specialist
 from top 
 where top =1 ;
 
 /* 10.	List the top 3 medical conditions associated with emergency admissions*/
 
 select medical_condition, count(*) as total_cases
 from hospital_data
 where admission_type = "emergency"
 group by medical_condition
 order by total_cases desc
 limit 3;
 
 /* 11.	Calculate the average length of stay for patients */
 SET SQL_SAFE_UPDATEs = 0;
 UPDATE hospital_data
SET admission_date = STR_TO_DATE(admission_date, '%d-%m-%Y');

  UPDATE hospital_data
SET discharge_date = STR_TO_DATE(discharge_date, '%d-%m-%Y');
 
 
 select round(avg(datediff( discharge_date, admission_date)),2) as avg_length_stay
 from hospital_data;
 
 /* 12.	Retrieve the % patients who were admitted for emergency treatment and discharged within 2 days.*/
 
 with cte1 as 
 (select count(*) as total_patient
 from hospital_data 
 where admission_type= "emergency"),
 
cte2 as 
( select count(*) as discharged_in_2days
 from hospital_data 
 where admission_type = "emergency" and
 datediff( discharge_date, admission_date) <= 2
 )
 
 select c2.discharged_in_2days, c1.total_patient,
 (c2.discharged_in_2days/c1.total_patient)*100 as pct
 from cte1 c1
 join cte2 c2 
 on 1=1;
 
	/*Identify hospitals where test result is normal (min 15count)*/
 
select hospital, count(test_results) as total_cnt
from hospital_data
where test_results= "normal"
group by hospital
having total_cnt > 15;

/* 16.	Find the top 5 hospitals with the highest number of patients discharged in the last 30 days.*/

select hospital,  count(*) as discharge_patient
from hospital_data
where discharge_date >= (select date_sub(max(discharge_date), Interval 30 day) from hospital_data)
group by hospital 
order by discharge_patient desc limit 5;

/* 17.	What percentage of doctors specialize in treating "Emergency" cases versus "Routine" cases?*/

with cte1 as 
( select admission_type, count(distinct doctor) as special_count
from hospital_data
where admission_type in ("emergency", "elective")
group by admission_type),

cte2 as 
(select sum(special_count) as total_count
from cte1)

select c1.admission_type,
(special_count *100/total_count) as pct
from cte1 c1
cross join cte2 c2 ;

/*16.	Analyze seasonal trends by identifying months or quarters with the highest patient admissions.*/
select month(admission_date) as month_no,
monthname(admission_date) as month_name, count(*) as total_patient
from hospital_data
group by month_no, month_name
order by month_no asc;

/* 17.	Determine the doctor who generated the most revenue for each year.*/

with rev as 
(select doctor, year(admission_date) as year, round(sum(billing_amount),2) as total_revenue
from hospital_data
group by doctor, year),

top as (select *,
dense_rank() over (partition by year order by total_revenue desc) as rnk
from rev)

select * 
from top
where rnk=1;

/* 18.	Identify the most common medical condition treated each year*/

with common as 
(select medical_condition, year(admission_date) as year, count(*) as condition_treated
from hospital_data
group by medical_condition, year),

rnk as 
(select *,
dense_rank () over (partition by year order by condition_treated desc) as rnk
from common)

select * 
from rnk
where rnk = 1;

/* 19.	Calculate the average billing amount for patients admitted in winter months (Dec, Jan, Feb). */

select year(admission_date) as year, round(avg(billing_amount),2) as avg_amount_winter
from hospital_data
where month(admission_date) in (12,1,2)
group by year
order by year asc;

/* Determine whether any specific medical conditions are more prevalent during particular quarters of the year.*/

with cond as 
(select concat('Q', quarter(admission_date)) as quarter,
 medical_condition, count(*) as total_condition
from hospital_data
group by medical_condition, quarter ),

rnk as 
(select *,
dense_rank () over(partition by quarter order by total_condition) as rnk
from cond)

select *
from rnk
where rnk=1;


with frequency as 
(select distinct(name) as patient, 
count(*) as visit
from hospital_data
group by patient)

select 
(count(case when visit >=2 then 1 end)/ count(*))* 100 as visit_pct
from frequency ;











 
 
 
 
 
 
 
 
 
 
 













